(()=>{const P=window.P||[],zh=s=>String(s||'').split(/[；;]/)[0].trim(),O={
available:['adj.','avail（可用、可获得）+ able（能够…的）→ 可用的；用于人时就是“有空的”。','I am available on Friday evening.','我周五晚上有空。',['valuable','avoidable','reliable'],'Is the meeting room ______ after lunch?'],
schedule:['n.','把 schedule 和“时间表”画面绑定：check my schedule = 看一下自己的日程。','I checked my schedule before making plans.','我在做安排之前先看了自己的日程。',['agenda','calendar','timetable'],'Let me check my ______ before I confirm the time.'],
free:['adj.','free 不只表示“免费”，说时间时 be free = 有空；和 available 对比记。','I am free after work today.','我今天下班后有空。',['available','vacant','spare'],'Are you ______ for coffee around six?'],
busy:['adj.','busy with + 名词 = 忙于某事；busy doing = 忙着做某事。','I am busy with work this afternoon.','我今天下午工作很忙。',['occupied','active','crowded'],'I am too ______ to talk right now; can I call you later?'],
'make it':['v. phr.','make it 口语里常表示“成功到达 / 能参加”，不是“制作它”。','I cannot make it at six, but seven works for me.','我六点赶不到，不过七点可以。',['make up','make out','make do'],'Sorry, I cannot ______ to dinner tonight.'],
reschedule:['v.','re-（再次）+ schedule（日程）→ 重新安排时间。','Can we reschedule the meeting for tomorrow?','我们可以把会议改到明天吗？',['rearrange','postpone','schedule'],'We may need to ______ because my flight is delayed.'],
confirm:['v.','con + firm：把事情“定牢”→ 确认；区分 conform（遵从）和 confront（面对）。','Please confirm the time before you leave.','你出发前请确认一下时间。',['conform','confront','confuse'],'Please ______ your reservation by email.'],
cancel:['v.','把 cancel 和 call off 一起记：两者都可以表示“取消计划 / 活动”。','I had to cancel our plan because I felt sick.','因为我不舒服，我不得不取消我们的计划。',['call off','postpone','remove'],'They had to ______ the outdoor event because of the rain.'],
convenient:['adj.','convenient 表示时间、地点或做法“方便”；常见 a convenient time / place。','Six o’clock is a convenient time for me.','六点对我来说是一个方便的时间。',['comfortable','suitable','available'],'Is this location ______ for everyone?'],
'plan ahead':['v. phr.','plan + ahead（往前）→ 把计划做在事情发生之前，也就是“提前计划”。','I like to plan ahead for busy weeks.','遇到忙碌的一周，我喜欢提前做好计划。',['think ahead','look ahead','plan on'],'If you travel during a holiday, it helps to ______.']};
const bank='accept actual active adapt advise agenda afford agree allow answer apologize approach arrange arrive avoid balance believe blame borrow budget calendar cancel careful cause change charge choice choose clarify compare complain confirm connect consider continue convenient crowded decide delay depend discuss discount easy exchange explain fair finish focus handle improve issue manage mention notice offer option order patient plan possible prepare price problem progress quiet reason reliable repair reply request respond safe save schedule serious share similar simple stable start stop strong support task trust understand update useful usual value valuable weak'.split(' '),all=P.flatMap(d=>d.w.map(x=>x[0])),allZh=P.flatMap(d=>d.w.map(x=>zh(x[1]))),D=(a,b)=>{a=a.toLowerCase();b=b.toLowerCase();let p=[...Array(b.length+1).keys()];for(let i=1;i<=a.length;i++){let c=[i];for(let j=1;j<=b.length;j++)c[j]=Math.min(c[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));p=c}return p[b.length]},pos=w=>O[w]?.[0]||(w.includes(' ')?'phr.':/(able|ible|ful|ous|ive|ed|y)$/.test(w)?'adj.':/(tion|ment|ness|ity|ship)$/.test(w)?'n.':/ly$/.test(w)?'adv.':'v./n.'),LX={};
P.forEach(d=>{let same=new Set(d.w.map(x=>x[0]));d.w.forEach(w=>{let q=w[0],p=pos(q),o=O[q],cf=o?.[4]||[...new Set([...bank,...all].filter(x=>x!==q&&!same.has(x)))].sort((a,b)=>D(q,a)-D(q,b)||Math.abs(q.length-a.length)-Math.abs(q.length-b.length)).slice(0,3),m=o?.[1]||(q.includes(' ')?`把 ${q.split(' ').join(' + ')} 当成一个整体短语记；核心意思是“${zh(w[1])}”。`:q.startsWith('re')&&q.length>6?`re- 常带“再次 / 重新”的感觉；把 ${q} 和“${zh(w[1])}”一起记。`:`把 ${q} 和“${zh(w[1])}”这个核心场景直接绑定。`),e=o?.[2]||(p==='adj.'?`It feels ${q} in this situation.`:p==='n.'?`We talked about ${q} before making a decision.`:q.includes(' ')?`I usually ${q} when plans change.`:`I need to ${q} this today.`),ez=o?.[3]||(p==='adj.'?`在这种情况下，感觉很${zh(w[1])}。`:p==='n.'?`我们在做决定前谈到了“${zh(w[1])}”。`:`这句话是在表达“${zh(w[1])}”这个意思。`),cl=o?.[5]||(p==='adj.'?'The situation felt ______ after the plan changed.':p==='n.'?'We talked about the ______ before making a decision.':q.includes(' ')?'I usually ______ when plans suddenly change.':'I need to ______ this before tomorrow.'),i=String(w[2]).toLowerCase().indexOf(q.toLowerCase()),cue=i<0?`${w[2]} · ___`:w[2].slice(0,i)+'___'+w[2].slice(i+q.length),zc=[...new Set(allZh.filter(x=>x!==zh(w[1])))].slice(0,3);LX[q]={pos:p,memory:m,example:e,exampleZh:ez,collocation:w[2],collocationParts:[q,cue],confusers:cf,zhConfusers:zc,cloze:cl,clozeOptions:[q,...cf]}})});window.LX=LX})();
